# https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build.environment]
    YOUR_NELTIFY_VARIABLE = "YOUR_NELTIFY_VARIABLE"
    base = "/"
    publish = "dist/"
    command = "yarn build"

[[plugins]]

[context.production]

[context.deploy-preview]
    publish = "dist/"