name: parcel-tsx-template ci
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      - name: Deps Installation
        run: npm install
        env:
          CI: true

      - name: Build Up
        run: npm run build

      - name: Unit Test
        run: npm run test
