name: parcel-tsx-template ci
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deps Installation
        run: yarn

      - name: Build Up
        run: yarn build

      - name: Unit Test
        run: yarn test
